version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: unilink-db
    restart: always
    environment:
      POSTGRES_USER: unilink_user
      POSTGRES_PASSWORD: unilink_password
      POSTGRES_DB: unilink_db
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Ferramenta visual opcional (pgAdmin) para facilitar a vida da equipe
  pgadmin:
    image: dpage/pgadmin4
    container_name: unilink-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@unilink.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: